_format_version: "3.0"
_transform: true

services:
  - name: sidecar-service
    url: http://sidecar:8080
    routes:
      - name: sidecar-route
        paths:
          - /api
        methods:
          - POST

plugins:
  - name: jwt
    service: sidecar-service
    config:
      key_claim_name: kid
      secret_is_base64: false
      claims_to_verify:
        - exp
